### ISSUE TITLE
FailSafe Mode doesn't work (Linksys WRT54G v2)

### ISSUE THREAD

**Issue by CK1-CK** [etactica/openwrt-backfire#1]
Hi,

OpenWRT Backfire Version 10.03.1

Unfortunately, it is not possible to boot into FailSafe mode with a Linksys WRT54g v2. You can press the reset button as many times as you like (short or long), the router always boots into normal mode.

https://openwrt.org/de/doc/howto/generic.failsafe

If you want to boot in the FailSafe Mode you have to shorten Pin 15 & 16 on the Flash element. Than you can Ping again the Router.
http://voidmain.is-a-geek.net/redhat/wrt54g_revival.html

**Comment by karlp** [comment]
This is not the openwrt project, but eTactica's fork of openwrt backfire for a product released at that time. It is emphatically not a place for support of generic devices.
